apiVersion: apps/v1
kind: Deployment
metadata:
  name: ebs-logs
  namespace: d1-pr-vfom-smtp
spec:
  selector:
    matchLabels:
      app: ebs-logs
  replicas: 1
  template:
    metadata:
      labels:
        app: ebs-logs
    spec:
     volumes:
        - name: shafique
          persistentVolumeClaim:
            claimName: shafique
     containers:
      - name: ebs-logs
        image: >-
          prodgitlab.vodafone.om:5050/shafique.kakati1/ebs_logs
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
            - name: shafique
              mountPath: /data
