kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ebs_logs
  annotations:
    volume.alpha.kubernetes.io/storage-class: "csi-manila-default"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2000Gi
